name = "BcdiStrain"
uuid = "3abd092d-e7bc-4ec6-94c6-c6851986118d"
authors = ["Jason Meziere"]
version = "0.0.1"

[deps]
BcdiCore = "72eb6a3e-ca63-4742-b260-85b05ca6d9e4"
BcdiTrad = "b788224a-5de6-46e5-9aeb-ad1a5171efd9"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.10.0"
BcdiCore = "0.0.1"
BcdiTrad = "0.0.1"
CUDA = "5.4.3"
LinearAlgebra = "1.5.0"
Statistics = "1.10.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
